// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordRequest) Reset() {
	*x = PasswordRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordRequest) ProtoMessage() {}

func (x *PasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordRequest.ProtoReflect.Descriptor instead.
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *PasswordRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordResponse) Reset() {
	*x = PasswordResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordResponse) ProtoMessage() {}

func (x *PasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordResponse.ProtoReflect.Descriptor instead.
func (*PasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *PasswordResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PasswordResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PasswordResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PasswordResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PasswordCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordCreateRequest) Reset() {
	*x = PasswordCreateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordCreateRequest) ProtoMessage() {}

func (x *PasswordCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordCreateRequest.ProtoReflect.Descriptor instead.
func (*PasswordCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PasswordCreateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PasswordCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PasswordUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordUpdateRequest) Reset() {
	*x = PasswordUpdateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUpdateRequest) ProtoMessage() {}

func (x *PasswordUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUpdateRequest.ProtoReflect.Descriptor instead.
func (*PasswordUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *PasswordUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PasswordUpdateRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *PasswordUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *CardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Bank          string                 `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Number        string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	DataEnd       string                 `protobuf:"bytes,5,opt,name=dataEnd,proto3" json:"dataEnd,omitempty"`
	SecretCode    string                 `protobuf:"bytes,6,opt,name=secretCode,proto3" json:"secretCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *CardResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardResponse) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CardResponse) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardResponse) GetDataEnd() string {
	if x != nil {
		return x.DataEnd
	}
	return ""
}

func (x *CardResponse) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

type CardCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Bank          string                 `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Number        string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	DataEnd       string                 `protobuf:"bytes,5,opt,name=dataEnd,proto3" json:"dataEnd,omitempty"`
	SecretCode    string                 `protobuf:"bytes,6,opt,name=secretCode,proto3" json:"secretCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardCreateRequest) Reset() {
	*x = CardCreateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardCreateRequest) ProtoMessage() {}

func (x *CardCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardCreateRequest.ProtoReflect.Descriptor instead.
func (*CardCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *CardCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CardCreateRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CardCreateRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardCreateRequest) GetDataEnd() string {
	if x != nil {
		return x.DataEnd
	}
	return ""
}

func (x *CardCreateRequest) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

type CardUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Bank          string                 `protobuf:"bytes,3,opt,name=bank,proto3" json:"bank,omitempty"`
	Number        string                 `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	DataEnd       string                 `protobuf:"bytes,5,opt,name=dataEnd,proto3" json:"dataEnd,omitempty"`
	SecretCode    string                 `protobuf:"bytes,6,opt,name=secretCode,proto3" json:"secretCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardUpdateRequest) Reset() {
	*x = CardUpdateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardUpdateRequest) ProtoMessage() {}

func (x *CardUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardUpdateRequest.ProtoReflect.Descriptor instead.
func (*CardUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *CardUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardUpdateRequest) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *CardUpdateRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardUpdateRequest) GetDataEnd() string {
	if x != nil {
		return x.DataEnd
	}
	return ""
}

func (x *CardUpdateRequest) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

type BinariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinariesRequest) Reset() {
	*x = BinariesRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinariesRequest) ProtoMessage() {}

func (x *BinariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinariesRequest.ProtoReflect.Descriptor instead.
func (*BinariesRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *BinariesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type BinariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinariesResponse) Reset() {
	*x = BinariesResponse{}
	mi := &file_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinariesResponse) ProtoMessage() {}

func (x *BinariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinariesResponse.ProtoReflect.Descriptor instead.
func (*BinariesResponse) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *BinariesResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BinariesResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BinariesResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BinariesCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinariesCreateRequest) Reset() {
	*x = BinariesCreateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinariesCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinariesCreateRequest) ProtoMessage() {}

func (x *BinariesCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinariesCreateRequest.ProtoReflect.Descriptor instead.
func (*BinariesCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{14}
}

func (x *BinariesCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BinariesCreateRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BinariesUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinariesUpdateRequest) Reset() {
	*x = BinariesUpdateRequest{}
	mi := &file_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinariesUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinariesUpdateRequest) ProtoMessage() {}

func (x *BinariesUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinariesUpdateRequest.ProtoReflect.Descriptor instead.
func (*BinariesUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *BinariesUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BinariesUpdateRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x16proto/gophkeeper.proto\x12\n" +
	"gophkeeper\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"'\n" +
	"\x0fPasswordRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"j\n" +
	"\x10PasswordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"_\n" +
	"\x15PasswordCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"Y\n" +
	"\x15PasswordUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"#\n" +
	"\vCardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x9a\x01\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\tR\x04bank\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12\x18\n" +
	"\adataEnd\x18\x05 \x01(\tR\adataEnd\x12\x1e\n" +
	"\n" +
	"secretCode\x18\x06 \x01(\tR\n" +
	"secretCode\"\x8f\x01\n" +
	"\x11CardCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\tR\x04bank\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12\x18\n" +
	"\adataEnd\x18\x05 \x01(\tR\adataEnd\x12\x1e\n" +
	"\n" +
	"secretCode\x18\x06 \x01(\tR\n" +
	"secretCode\"\x89\x01\n" +
	"\x11CardUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04bank\x18\x03 \x01(\tR\x04bank\x12\x16\n" +
	"\x06number\x18\x04 \x01(\tR\x06number\x12\x18\n" +
	"\adataEnd\x18\x05 \x01(\tR\adataEnd\x12\x1e\n" +
	"\n" +
	"secretCode\x18\x06 \x01(\tR\n" +
	"secretCode\"'\n" +
	"\x0fBinariesRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"L\n" +
	"\x10BinariesResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\"A\n" +
	"\x15BinariesCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\";\n" +
	"\x15BinariesUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\x8c\x01\n" +
	"\x05Users\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse\x12<\n" +
	"\x05Login\x12\x18.gophkeeper.LoginRequest\x1a\x19.gophkeeper.LoginResponse2\x9f\x02\n" +
	"\tPasswords\x12@\n" +
	"\x03Get\x12\x1b.gophkeeper.PasswordRequest\x1a\x1c.gophkeeper.PasswordResponse\x12F\n" +
	"\x03Add\x12!.gophkeeper.PasswordCreateRequest\x1a\x1c.gophkeeper.PasswordResponse\x12I\n" +
	"\x06Update\x12!.gophkeeper.PasswordUpdateRequest\x1a\x1c.gophkeeper.PasswordResponse\x12=\n" +
	"\x06Delete\x12\x1b.gophkeeper.PasswordRequest\x1a\x16.google.protobuf.Empty2\xff\x01\n" +
	"\x05Cards\x128\n" +
	"\x03Get\x12\x17.gophkeeper.CardRequest\x1a\x18.gophkeeper.CardResponse\x12>\n" +
	"\x03Add\x12\x1d.gophkeeper.CardCreateRequest\x1a\x18.gophkeeper.CardResponse\x12A\n" +
	"\x06Update\x12\x1d.gophkeeper.CardUpdateRequest\x1a\x18.gophkeeper.CardResponse\x129\n" +
	"\x06Delete\x12\x17.gophkeeper.CardRequest\x1a\x16.google.protobuf.Empty2\x9e\x02\n" +
	"\bBinaries\x12@\n" +
	"\x03Get\x12\x1b.gophkeeper.BinariesRequest\x1a\x1c.gophkeeper.BinariesResponse\x12F\n" +
	"\x03Add\x12!.gophkeeper.BinariesCreateRequest\x1a\x1c.gophkeeper.BinariesResponse\x12I\n" +
	"\x06Update\x12!.gophkeeper.BinariesUpdateRequest\x1a\x1c.gophkeeper.BinariesResponse\x12=\n" +
	"\x06Delete\x12\x1b.gophkeeper.BinariesRequest\x1a\x16.google.protobuf.EmptyB)Z'github.com/MultikPatin/gophkeeper/protob\x06proto3"

var (
	file_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_proto_gophkeeper_proto_rawDescData []byte
)

func file_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)))
	})
	return file_proto_gophkeeper_proto_rawDescData
}

var file_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_gophkeeper_proto_goTypes = []any{
	(*RegisterRequest)(nil),       // 0: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),      // 1: gophkeeper.RegisterResponse
	(*LoginRequest)(nil),          // 2: gophkeeper.LoginRequest
	(*LoginResponse)(nil),         // 3: gophkeeper.LoginResponse
	(*PasswordRequest)(nil),       // 4: gophkeeper.PasswordRequest
	(*PasswordResponse)(nil),      // 5: gophkeeper.PasswordResponse
	(*PasswordCreateRequest)(nil), // 6: gophkeeper.PasswordCreateRequest
	(*PasswordUpdateRequest)(nil), // 7: gophkeeper.PasswordUpdateRequest
	(*CardRequest)(nil),           // 8: gophkeeper.CardRequest
	(*CardResponse)(nil),          // 9: gophkeeper.CardResponse
	(*CardCreateRequest)(nil),     // 10: gophkeeper.CardCreateRequest
	(*CardUpdateRequest)(nil),     // 11: gophkeeper.CardUpdateRequest
	(*BinariesRequest)(nil),       // 12: gophkeeper.BinariesRequest
	(*BinariesResponse)(nil),      // 13: gophkeeper.BinariesResponse
	(*BinariesCreateRequest)(nil), // 14: gophkeeper.BinariesCreateRequest
	(*BinariesUpdateRequest)(nil), // 15: gophkeeper.BinariesUpdateRequest
	(*emptypb.Empty)(nil),         // 16: google.protobuf.Empty
}
var file_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.Users.Register:input_type -> gophkeeper.RegisterRequest
	2,  // 1: gophkeeper.Users.Login:input_type -> gophkeeper.LoginRequest
	4,  // 2: gophkeeper.Passwords.Get:input_type -> gophkeeper.PasswordRequest
	6,  // 3: gophkeeper.Passwords.Add:input_type -> gophkeeper.PasswordCreateRequest
	7,  // 4: gophkeeper.Passwords.Update:input_type -> gophkeeper.PasswordUpdateRequest
	4,  // 5: gophkeeper.Passwords.Delete:input_type -> gophkeeper.PasswordRequest
	8,  // 6: gophkeeper.Cards.Get:input_type -> gophkeeper.CardRequest
	10, // 7: gophkeeper.Cards.Add:input_type -> gophkeeper.CardCreateRequest
	11, // 8: gophkeeper.Cards.Update:input_type -> gophkeeper.CardUpdateRequest
	8,  // 9: gophkeeper.Cards.Delete:input_type -> gophkeeper.CardRequest
	12, // 10: gophkeeper.Binaries.Get:input_type -> gophkeeper.BinariesRequest
	14, // 11: gophkeeper.Binaries.Add:input_type -> gophkeeper.BinariesCreateRequest
	15, // 12: gophkeeper.Binaries.Update:input_type -> gophkeeper.BinariesUpdateRequest
	12, // 13: gophkeeper.Binaries.Delete:input_type -> gophkeeper.BinariesRequest
	1,  // 14: gophkeeper.Users.Register:output_type -> gophkeeper.RegisterResponse
	3,  // 15: gophkeeper.Users.Login:output_type -> gophkeeper.LoginResponse
	5,  // 16: gophkeeper.Passwords.Get:output_type -> gophkeeper.PasswordResponse
	5,  // 17: gophkeeper.Passwords.Add:output_type -> gophkeeper.PasswordResponse
	5,  // 18: gophkeeper.Passwords.Update:output_type -> gophkeeper.PasswordResponse
	16, // 19: gophkeeper.Passwords.Delete:output_type -> google.protobuf.Empty
	9,  // 20: gophkeeper.Cards.Get:output_type -> gophkeeper.CardResponse
	9,  // 21: gophkeeper.Cards.Add:output_type -> gophkeeper.CardResponse
	9,  // 22: gophkeeper.Cards.Update:output_type -> gophkeeper.CardResponse
	16, // 23: gophkeeper.Cards.Delete:output_type -> google.protobuf.Empty
	13, // 24: gophkeeper.Binaries.Get:output_type -> gophkeeper.BinariesResponse
	13, // 25: gophkeeper.Binaries.Add:output_type -> gophkeeper.BinariesResponse
	13, // 26: gophkeeper.Binaries.Update:output_type -> gophkeeper.BinariesResponse
	16, // 27: gophkeeper.Binaries.Delete:output_type -> google.protobuf.Empty
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gophkeeper_proto_init() }
func file_proto_gophkeeper_proto_init() {
	if File_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gophkeeper_proto_rawDesc), len(file_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_proto_gophkeeper_proto_depIdxs,
		MessageInfos:      file_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_proto_gophkeeper_proto = out.File
	file_proto_gophkeeper_proto_goTypes = nil
	file_proto_gophkeeper_proto_depIdxs = nil
}
